x-airflow-image: &airflow_image starias/airflow-spark

x-spark-common-properties: &spark_common_properties
  image: starias/spark-kafka
  volumes:
   - .jobs:/opt/bitnami/spark/jobs
  networks:
    - backend
  restart: always
  
x-spark-worker-environment: &spark_worker_environment
  SPARK_MODE: worker
  SPARK_WORKER_CORES: 2
  SPARK_WORKER_MEMORY: 8G
  SPARK_MASTER_URL: spark://spark-master:7077
  TRAINED_MODELS_PATH: ${TRAINED_MODELS_PATH}

x-environment: &airflow_environment
  - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
  - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
  - AIRFLOW__CELERY__BROKER_URL=redis://:@redis:6379/2
  - AIRFLOW__CORE__FERNET_KEY=''
  #- AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__DETABASE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__CORE__STORE_DAG_CODE=True
  - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  - AIRFLOW_CONN_POSTGRES_DEFAULT=postgresql://airflow:airflow@postgres/airflow
  - AIRFLOW__CORE__FERNET_KEY=EJ7tt4r06HhjniZKjNICTqaOGotA2Jfa9EF7KyW-7Wc=
  - AIRFLOW__CELERY__WORKERS=2
  - AIRFLOW__CELERY__WORKER_CONCURRENCY=2
  #- AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:B9#fS!4qW@p8zK*1@postgres/airflow-db
  - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
  - CHECKPOINT_DIR=${CHECKPOINT_DIR}
  - REDIS_HOST=${REDIS_HOST}
  - MONGO_DB_URI=${MONGO_DB_URI}
  - AIRFLOW__CORE__DEFAULT_TIMEZONE=UTC
  - AIRFLOW__EMAIL__EMAIL_BACKEND=airflow.utils.email.send_email_smtp
  - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
  - AIRFLOW__SMTP__START_TLS=False
  - AIRFLOW__SMTP__SMTP_SSL=False
  - AIRFLOW__SMTP__SMTP_PORT=587
  - TRAINED_MODELS_PATH=${TRAINED_MODELS_PATH}
  
services:
  postgres:
    restart: always
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      #POSTGRES_DB: admin
    networks:
      - backend
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - /home/starias/africa_news_api/database/init:/docker-entrypoint-initdb.d

networks:
  backend:
    name: backend-network 
    driver: bridge
  
secrets:
  smtp_user:
    file: ./secrets/smtp_user/user.txt

#volumes:
  #postgres_data:
    