-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS public.article;

DROP TABLE IF EXISTS public.author;
DROP TABLE IF EXISTS public.country;
DROP TABLE IF EXISTS public.language;
DROP TABLE IF EXISTS public.category;
DROP TABLE IF EXISTS public.extractor;

CREATE TABLE IF NOT EXISTS public.author
(
    author_id serial NOT NULL,
    author_name character varying(100), -- made nullable
    author_url text, -- made nullable
    PRIMARY KEY (author_id)
);


CREATE TABLE IF NOT EXISTS public.country
(
    country_id smallserial NOT NULL,
    country_name character varying(100) , -- made nullable
    country_code character(2) NOT NULL,
    PRIMARY KEY (country_id)
);


CREATE TABLE IF NOT EXISTS public.language
(
    lang_id smallserial NOT NULL,
    lang_name character varying(100) NOT NULL,
    lang_code character(2) NOT NULL,
    PRIMARY KEY (lang_id)
);


CREATE TABLE IF NOT EXISTS public.category
(
    category_id smallserial NOT NULL,
    category_name character varying(100), -- made nullable
    PRIMARY KEY (category_id)
);



CREATE TABLE IF NOT EXISTS public.extractor
(
    extractor_id smallserial NOT NULL,
    extractor_name character(100) NOT NULL,
    extractor_description text,
    extractor_url text,
    PRIMARY KEY (extractor_id)
);

CREATE TABLE IF NOT EXISTS public.article
(
    article_id SERIAL NOT NULL, -- Updated to serial
    author_id integer NOT NULL,
    category_id smallint NOT NULL,
    extractor_id smallint,
    country_id smallint NOT NULL,
    lang_id smallint NOT NULL,
    publication_date date,
    title text,
    description text,
    img_url text,
    url text,
    content_preview text,
    content text,
    source character(100),
    PRIMARY KEY (article_id)
);

ALTER TABLE IF EXISTS public.article
    ADD FOREIGN KEY (author_id)
    REFERENCES public.author (author_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.article
    ADD FOREIGN KEY (country_id)
    REFERENCES public.country (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.article
    ADD FOREIGN KEY (category_id)
    REFERENCES public.category (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.article
    ADD FOREIGN KEY (extractor_id)
    REFERENCES public.extractor (extractor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.article
    ADD FOREIGN KEY (lang_id)
    REFERENCES public.language (lang_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;